### ISSUE TITLE
Missing support for rack socket hijacking API?

### ISSUE THREAD

**Issue by ketan** [jruby/jruby-rack#202] opened 2015-12-25 09:29 UTC
I'm looking at the source code and find that support for the rack socket hijacking api (https://github.com/rack/rack/pull/481) is missing both in master and 1.1-stable branch.

I assumed that since jruby-rack ships rack 1.5.x, that the hijack api is implemented, is this still in the works?

**Comment by kares** [comment] 2015-12-25 11:25
not implemented as no one has attempted to do so or support us: closing as duplicate of https://github.com/jruby/jruby-rack/issues/167 also see https://github.com/jruby/jruby-rack/issues/168

**Closed by kares** 2015-12-25 11:25 UTC
