### ISSUE TITLE
Getting an error while to load gem

### ISSUE THREAD

**Issue by pytong** [jruby/jruby-rack#207] opened 2016-09-24 01:25 UTC
All the gems in Gemfile was loaded properly except this one. I checked the war file and this gem is where it is supposed to be at 
WEB-INF/gems/gems/paperclip-4.3.7/lib/paperclip
and WEB-INF/gems/gems contains all the other gems.

JRuby-Rack startup
There was an error while trying to load the gem 'paperclip'.
Gem Load Error is: Unknown error - <STDERR>
Backtrace for gem load error is:
org/jruby/RubyIO.java:1448:in `write'
org/jruby/RubyIO.java:1419:in `write'
org/jruby/RubyKernel.java:956:in `require'
/tmp/jetty-0.0.0.0-8100.release.f1a4464.war-_-any-5996302710614289189.dir/webapp/WEB-INF/gems/gems/paperclip-4.3.7/lib/paperclip/storage.rb:1:in `<main>'

the file storage.rb has this content
`require "paperclip/storage/filesystem"`
`require "paperclip/storage/fog"`
`require "paperclip/storage/s3"`

and the file paperclip/storage/filesystem exists at
WEB-INF/gems/gems/paperclip-4.3.7/lib/paperclip/storage/filesystem.rb in the war file

What might be wrong?

**Comment by pytong** [comment] 2016-09-25 01:35
Is there any tools I can use for debugging the startup process?

**Comment by kares** [comment] 2016-09-25 10:54
you might try turning debug on for JRuby's loadService (check your local --properties) ... this seems like an issue with loading although there should be more details printed. you should also try upgrading jruby (bundle update jruby-jars) since you did not mention whether its latest 1.7/9K

**Comment by mkristian** [comment] 2016-09-26 05:57
an attempt to "write" something sounds like bundler trying to update the
Gemfile.lock - could be outdated !?

**Comment by andreimaxim** [comment] 2016-09-26 14:10
I work with @pytong and the issue seems to be related to jruby-rack but it might be caused by an internal tool that bundles the apps in a WAR file so until we can rule out some bad code on our side, I'd suggest we close this bug for now and, if need be, we'll come back with a more detailed error.

Thank you for your help so far!

**Closed** 2016-09-26 14:21 UTC

**Comment by pytong** [comment] 2016-09-26 20:28
Thanks for all of your help. It was actually an issue with the content of config/warble.rb. After I added Gemfile and Gemfile.lock to config.includes, the error is gone.
